### PR TITLE
Updating code to build pipeline using multijob

### PR DESCRIPTION
**Pull request by suvirp**
This change will support pipeline jobs in a multijob job. Change was originally suggested by Simon Weber in https://issues.jenkins-ci.org/browse/JENKINS-38825. Can you please review and merge the change.

Change-Id: I837bc6e757c7b0dbcc90ee52823540fb8c4df8f1

### CODE REVIEW

**Comment by yorammi** [comment]
Thanks @suvirp for the pull request!
Since merging this pull request will force users to switch to Jenkins 2.31 and up, and there is a large usage of tikal-multijob-plugin on servers with Jenkins 1.x that are not planned to switch to 2.x servers, we must **carefully consider** whether to merge this PR, split the versions of the plugin or find another alternative.
Still, we see that many voted for the above-mentioned issue and that many others also complain about not able to run pipeline jobs with multiJob.
Therefore, we'll check the PR and if works OK, we'll have a decision about how to merge it.

**Comment by suvirp** [comment]
> @suvirp I've tested locally you PR and it works fine as expected, running a pipeline job inside a mutiJob build.
> Still, we'll consider how to merge it soon.

Ok, Thanks for considering my PR. Hope to see it get merged soon.

**Comment by yorammi** [comment]
@suvirp It's been approved to merge the PR. Soon we'll release a new version.

**Comment by suvirp** [comment]
Thats great news.
Thank you.

**Comment by yorammi** [comment]
Version 1.32 released and contains this PR of @suvirp

**Comment by suvirp** [comment]
Thank you!

**Pull request merged**
