### PR TITLE
fix bug running jobs sequentially - ordering JENKINS-37351

### PR DESCRIPTION
**Pull request by Andykaban**

### CODE REVIEW

**Comment by lyenliang** [comment]
Thank you @Andykaban. This patch saves me a lot of time.

**Comment by chrisdmartinuk** [comment]
Have tested 'ordering of jobs', and confirmed it's working correctly. Thanks @Andykaban.

**Comment by Andykaban** [comment]
Can anyone tell me to push this request?

**Comment by tiger-seo** [comment]
@itaior I'm sorry to trouble you, but can you please look to this bug fix ?? thank you much

**Pull request merged**
