### PR TITLE
Verify env variables are identical on resume

### PR DESCRIPTION
**Pull request by dcendents**
Hi,

I've added a new option to the configuration page to verify that environment variables are identical when resuming a build.

This can be used to validate the build we are resuming from is in a consistent state with the workspace. e.g.: GIT_COMMIT

When the variable valuess are different, a full build is triggered instead.

This property is optional, therefore the current behavior is maintained.

Cheers,

### CODE REVIEW

**Comment by emoshaya-cognito** [comment]
This is definitely a big thumbs up from me!

**Comment by hagzag** [comment]
@dcendents This is awesome and looks like a good fix / feature would you be kind enough to review this PR after the long pursue we have had with Jenkins 2.0 security vulnerabilities which were 1st prio in this upcoming release.

Thanks again looking forward for it ASAP if you think it's a quick one I will wait with the 1.22 release for tomorrow.

**Comment by dcendents** [comment]
Thanks @hagzag, if you can wait I will update it tonight.
I haven't at the changes on master but my modifications were minor so I don't expect any problem.

I'll let you know either way in a few hours.

**Comment by hagzag** [comment]
@dcendents thanks, I will wait with the release then.

**Comment by dcendents** [comment]
Something seems to be broken on the build server, or it might affect some nodes only:

```
[WARNING] The POM for org.apache.maven:maven-plugin-api:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.maven:maven-project:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.maven:maven-artifact:jar:2.2.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.maven:maven-plugin-api:jar:3.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.apache.maven:maven-artifact:jar:3.0.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

Then it fails with the enforcer complaining the groupId cannot be null for artifact {null:null:null:jar}

**Comment by dcendents** [comment]
It ssems to be an issue with jenkins, same error with the latest build of the junit plugin: https://jenkins.ci.cloudbees.com/job/plugins/job/junit-plugin/210/console

**Comment by dcendents** [comment]
@hagzag the build passed with the latest rebase, I'd be grateful if you can merge it before the 1.22 release.

Thanks

**Comment by hagzag** [comment]
Done ;)

**Comment by dcendents** [comment]
Thanks @hagzag

**Pull request merged**
