### PR TITLE
Replaced png build status icons with svg

### PR DESCRIPTION
**Pull request by balakine**
All I want is a green ball, but that plugin is deprecated. Might as well migrate to svg here.

### CODE REVIEW

**Comment by balakine** [comment]
Oops, didn't mean to close it.

**Comment by balakine** [comment]
Sorry to bother you @NotMyFault, but you are the last person who touched this plugin, so you are it 😄. If you could take a look I would greatly appreciate it. Or I can ask to get added to the maintainers, if you think it's easier.

**Comment by NotMyFault** [comment]
> Sorry to bother you @NotMyFault, but you are the last person who touched this plugin, so you are it 😄. If you could take a look I would greatly appreciate it. Or I can ask to get added to the maintainers, if you think it's easier.

I'm not a developer or maintainer of the plugin. Generally, the plugin is end of life, don't expect future activity here.
Out of courtesy, I'll merge the PR nonetheless :)

**Comment by balakine** [comment]
> > Sorry to bother you @NotMyFault, but you are the last person who touched this plugin, so you are it 😄. If you could take a look I would greatly appreciate it. Or I can ask to get added to the maintainers, if you think it's easier.
> 
> I'm not a developer or maintainer of the plugin. Generally, the plugin is end of life, don't expect future activity here. Out of courtesy, I'll merge the PR nonetheless :)

Thank you! So if I do want future activity here I should get myself on the maintainers list, right?

**Pull request merged**
