### PR TITLE
[JENKINS-20468] Added flyweight configuration

### PR DESCRIPTION
**Pull request by sshelomentsev**
Added a new project that has the same logic as the MultiJob Project, but is a flyweight task and as such it is not counting as a builder.

### CODE REVIEW

**Comment by raags** [comment]
Hi, has anyone had a chance to look at this change? this will be a good feature to have.

**Comment by sshelomentsev** [comment]
Hi @raags 
We found another way to make job flyweight using build wrapper in runtime. It works for any project type. So I think makes no sense to propose another one configuration to this plugin.

**Comment by raags** [comment]
@sshelomentsev oh, can you point me to how that is done? Thanks

**Comment by sshelomentsev** [comment]
@raags 

Create a class extends from Job and implements Queue.FlyweightTask, ParameterizedJobMixIn.ParameterizedJob like

public class JobWrapper extends Job implements Queue.FlyweightTask, ParameterizedJobMixIn.ParameterizedJob {

private final Queue.Task task;

    public JobWrapper(Queue.Task task) {
        super(((Job) task).getParent(), task.getName());
        this.task = task;
    }
}

next,
you have class that instance of Queue.Task, for example, AbstractProject
create a new instance 
final JobWrapper wrapper = new JobWrapper(task);
ParameterizedJobMixIn mixIn = new ParameterizedJobMixIn() {
                @Override
                protected Job asJob() {
                    return wrapper;
                }
            };
mixIn.scheduleBuild2(quietPeriod, actions.toArray(new Action[actions.size()]));

Scheduled build will flyweight

**Pull request closed without merging**
